# Shared by the main build and the RHEL dependency-only preflight.
include_guard(GLOBAL)
include(FetchContent)
if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()
if(POLICY CMP0144)
  cmake_policy(SET CMP0144 NEW)
endif()
if(POLICY CMP0159)
  cmake_policy(SET CMP0159 NEW)
endif()
include(${CMAKE_CURRENT_LIST_DIR}/ApiHeaderVersions.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ApiBoost.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ApiJson.cmake)
