function(facts_header_root root header output)
  foreach(candidate "${root}" "${root}/include" "${root}/single_include")
    if(EXISTS "${candidate}/${header}")
      set(${output} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${output} "" PARENT_SCOPE)
endfunction()

function(facts_boost_version directory output)
  set(${output} 0 PARENT_SCOPE)
  if(EXISTS "${directory}/boost/version.hpp"
      AND EXISTS "${directory}/boost/asio.hpp"
      AND EXISTS "${directory}/boost/beast.hpp")
    file(STRINGS "${directory}/boost/version.hpp" definition
      REGEX "^#define BOOST_VERSION [0-9]+")
    string(REGEX MATCH "[0-9]+" version "${definition}")
    if(version)
      set(${output} "${version}" PARENT_SCOPE)
    endif()
  endif()
endfunction()

function(facts_json_version directory output)
  set(${output} 0 PARENT_SCOPE)
  foreach(header json.hpp detail/abi_macros.hpp detail/macro_scope.hpp)
    if(NOT EXISTS "${directory}/nlohmann/${header}")
      continue()
    endif()
    file(STRINGS "${directory}/nlohmann/${header}" definitions
      REGEX "^#define NLOHMANN_JSON_VERSION_(MAJOR|MINOR|PATCH) +[0-9]+")
    if(NOT definitions)
      continue()
    endif()
    foreach(part MAJOR MINOR PATCH)
      string(REGEX MATCH "NLOHMANN_JSON_VERSION_${part} +([0-9]+)" match "${definitions}")
      set(${part} "${CMAKE_MATCH_1}")
    endforeach()
    if(NOT "${MAJOR}.${MINOR}.${PATCH}" MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
      continue()
    endif()
    set(${output} "${MAJOR}.${MINOR}.${PATCH}" PARENT_SCOPE)
    return()
  endforeach()
endfunction()
