get:
  operationId: v2Settings
  tags:
  - resources-v2
  summary: Read public server settings
  responses:
    '200':
      description: Read public server settings
      content:
        application/json:
          schema:
            $ref: '../../openapi.yaml#/components/schemas/V2Settings'
    '400':
      $ref: '../../openapi.yaml#/components/responses/V2Error400'
    '401':
      $ref: '../../openapi.yaml#/components/responses/V2Error401'
    '405':
      $ref: '../../openapi.yaml#/components/responses/V2Error405'
    '415':
      $ref: '../../openapi.yaml#/components/responses/V2Error415'
    '404':
      $ref: '../../openapi.yaml#/components/responses/V2Error404'
    '409':
      $ref: '../../openapi.yaml#/components/responses/V2Error409'
    '422':
      $ref: '../../openapi.yaml#/components/responses/V2Error422'
    '429':
      $ref: '../../openapi.yaml#/components/responses/V2Error429'
    '503':
      $ref: '../../openapi.yaml#/components/responses/V2Error503'
    default:
      $ref: '../../openapi.yaml#/components/responses/V2ErrorDefault'
