"""Generated by scripts/generate_openapi.py from src/apis/openapi/openapi.yaml."""
# Lifecycle source: scripts/openapi_codegen/templates/client.py.in

from types import TracebackType
from typing import Self

import httpx

from .arguments import arguments, command_path, identifier
from .configuration import auth_headers, base_address, seconds
from .decoding import command_catalog, job, object_list
from .endpoints import endpoint
from .models import Job
from .polling import validate_wait, wait
from .transport import request, request_text


class Client:
    """A reusable HTTP client; close it or use a ``with`` block."""

    def __init__(
        self, base_url: str, *, token: str | None = None, timeout: float = 10.0,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        self._http = httpx.Client(
            base_url=base_address(base_url), headers=auth_headers(token),
            timeout=seconds(timeout, "timeout"), transport=transport,
            follow_redirects=False, trust_env=False,
        )

    def __enter__(self) -> Self:
        self._http.__enter__()
        return self

    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        self._http.__exit__(exc_type, exc, traceback)

    def close(self) -> None:
        self._http.close()

    def health(self) -> dict[str, object]:
        return request(self._http, *endpoint("health"))

    def openapi(self) -> dict[str, object]:
        return request(self._http, *endpoint("openapi"))

    def openapi_yaml(self) -> str:
        return request_text(self._http, *endpoint("openapiYaml"))

    def commands(self) -> list[dict[str, object]]:
        return command_catalog(request(self._http, *endpoint("commands")))

    def list_jobs(self) -> list[Job]:
        route = endpoint("listJobs")
        value = request(self._http, *route)
        return [job(item, metadata=True) for item in object_list(value, "jobs")]

    def submit(self, *argv: str) -> Job:
        return job(request(self._http, *endpoint("submit"), body=arguments(argv)))

    def get_job(self, job_id: str) -> Job:
        return job(request(self._http, *endpoint("getJob", id=identifier(job_id))))

    def cancel_job(self, job_id: str) -> Job:
        return job(request(self._http, *endpoint("cancelJob", id=identifier(job_id))))

    def watch_status(self) -> dict[str, object]:
        return request(self._http, *endpoint("watchStatus"))

    def shutdown(self) -> dict[str, object]:
        return request(self._http, *endpoint("shutdown"))

    def command(self, path: str, *argv: str) -> Job:
        path = command_path(path)
        body = arguments(argv, prefix_count=len(path.split("/")))
        route = endpoint("command", commandPath=path)
        return job(request(self._http, *route, body=body))

    def wait(
        self, job_id: str, *, timeout: float | None = None, poll_interval: float = 0.1,
    ) -> Job:
        return wait(self._http, job_id, timeout, poll_interval)

    def run(
        self, *argv: str, timeout: float | None = None, poll_interval: float = 0.1,
        check: bool = True,
    ) -> Job:
        validate_wait(timeout, poll_interval)
        result = self.wait(
            self.submit(*argv).id, timeout=timeout, poll_interval=poll_interval,
        )
        return result.raise_for_status() if check else result
