INVALID_YAML = {
    "malformed": "conf_root: [bad",
    "duplicate": "extra_args: []\nextra_args: []",
    "unknown": "surprise: true",
    "null-root": "conf_root: null",
    "empty-root": 'conf_root: ""',
    "number-root": "conf_root: 123",
    "sequence-root": "conf_root: []",
    "null-template": "conf_template: null",
    "empty-template": 'conf_template: ""',
    "mapping-template": "conf_template: {}",
    "null-args": "extra_args: null",
    "scalar-args": "extra_args: -DVALUE",
    "mapping-args": "extra_args: {}",
    "number-arg": "extra_args: [1]",
    "boolean-arg": "extra_args: [true]",
    "null-arg": "extra_args: [null]",
    "mapping-arg": "extra_args: [{}]",
    "sequence-arg": "extra_args: [[]]",
    "nul-arg": r'extra_args: ["a\0b"]',
    "newline-arg": r'extra_args: ["a\nb"]',
    "tag": "extra_args: [!!str hello]",
    "anchor": "extra_args: &a [hello]",
    "alias": "extra_args: [*missing]",
    "documents": "{}\n---\n{}",
    "not-map": "[hello]",
    "nul-root": r'conf_root: "a\0b"',
    "newline-root": r'conf_root: "a\nb"',
}
