import pytest
from pytest_bdd import given, scenarios, then, when

from facts_tool import FactsToolError
from facts_tool.queryplan import (
    codebase,
    eq,
    nodes,
    order_by,
    select,
    sites,
    start,
    symbol,
    view,
)

scenarios("../features/native-database.feature")


@given("a database pair generated by the native facts-tool", target_fixture="cb")
def native_pair(native_codebase):
    return native_codebase


@when("I query native symbols sites and project files")
def query_native(cb, world):
    world["symbols"] = cb.executor.run((start(codebase()) | nodes()).plan).nodes
    world["holders"] = cb.executor.run(start(symbol("Holder")).plan).nodes
    edges = start(codebase()) | view("edge") | nodes(eq("kind", "calls"))
    query = edges | sites() | select(("source_id", "destination_id", "file", "line"))
    world["sites"] = cb.executor.run((query | order_by(("file", "line"))).plan).rows
    world["files"] = cb.executor.run(
        (start(codebase()) | view("file") | nodes()).plan
    ).nodes
    with pytest.raises(FactsToolError) as raised:
        cb.executor.run((edges | sites() | view("site")).plan)
    world["site_error"] = raised.value.code


@then("native kinds ambiguity sites and both databases are preserved")
def verify_native(cb, world):
    kinds = {(row["qualified_name"], row["kind_id"], row["kind"])
             for row in world["symbols"]}
    assert ("Color", 6, "enum") in kinds
    assert ("save", 13, "function") in kinds
    assert ("Holder::T", 28, "template_type_parm") in kinds
    assert [row["id"] for row in world["holders"]] == [4294967296, 4294967300]
    assert [row["line"] for row in world["sites"]] == [14, 15, 15]
    assert world["site_error"] == "E_STAGE"
    assert world["files"][0]["name"] == "source.cpp"
    assert cb.provenance.facts.schema.user_version == 10
