"""Render small native routing tables, limits, and the bundled document."""
import json
import re

from .validation import LIMITS, operations

PREFIX = "src/apis/generated/"
NOTICE = "// Generated by scripts/generate_openapi.py; do not edit.\n"
NAMESPACE = "namespace facts::apis::generated {\n"


def header(body: str, includes: str) -> str:
    return NOTICE + "#pragma once\n" + includes + "\n" + NAMESPACE + body + "}\n"


def render_native(document: dict) -> dict[str, str]:
    rows = list(operations(document))
    identifiers = ", ".join(operation["operationId"] for _, _, operation in rows)
    entries = []
    for path, method, operation in rows:
        parameter = next(iter(re.findall(r"\{([^}]+)\}", path)), "")
        literals = ", ".join(json.dumps(value) for value in (method.upper(), path, parameter))
        entries.append(f"  Route{{{literals}, Operation::{operation['operationId']}}},")
    routes = (f"enum class Operation {{ {identifiers} }};\n"
              "struct Route {\n  std::string_view method, path, parameter;\n"
              "  Operation operation;\n};\n"
              f"inline constexpr std::array<Route, {len(rows)}> routes{{{{\n"
              + "\n".join(entries) + "\n}};\n")
    limits = "".join(f"inline constexpr std::size_t {name} = "
                     f"{document['x-facts-limits'][name]};\n" for name in LIMITS)
    output = {
        PREFIX + "Routes.h": header(routes, "#include <array>\n#include <string_view>\n"),
        PREFIX + "Limits.h": header(limits, "#include <cstddef>\n"),
        PREFIX + "Spec.h": header("std::string_view specification();\n", "#include <string_view>\n"),
    }
    serialized = json.dumps(document, ensure_ascii=True, indent=2) + "\n"
    lines = serialized.splitlines(keepends=True)
    parts = [lines[start:start + 90] for start in range(0, len(lines), 90)]
    includes = []
    for index, part in enumerate(parts):
        filename = f"SpecPart{index:03}.inc"
        output[PREFIX + filename] = NOTICE + "".join(json.dumps(line) + "\n" for line in part)
        includes.append(f'#include "{filename}"')
    output[PREFIX + "Spec.cpp"] = (NOTICE + '#include "Spec.h"\n\n' + NAMESPACE
        + "std::string_view specification() {\n  static constexpr char document[] =\n"
        + "\n".join(includes) + "\n;\n  return document;\n}\n}\n")
    return output
