FACT_VIEWS = {
    "symbol",
    "parameter",
    "template_parameter",
    "template_argument",
    "edge",
    "site",
    "definition",
    "enumeration",
    "enumerator",
    "initializer",
    "return_type",
}
PROJECT_VIEWS = {"repository", "clone", "component", "directory", "file"}
VIEWS = FACT_VIEWS | PROJECT_VIEWS
SYMBOL_FIELDS = {
    "id",
    "node",
    "kind",
    "kind_id",
    "sub_kind",
    "lang",
    "properties",
    "usr",
    "name",
    "qualified_name",
    "spelling",
    "line",
    "col",
    "offset",
    "file_id",
    "file",
    "access",
    "ref_qualifier",
    "constant_evaluation",
    "is_definition",
    "is_implicit",
    "is_static",
    "is_virtual",
    "is_const",
    "is_volatile",
    "is_inline",
    "is_pure",
    "is_override",
    "is_external",
    "is_variadic",
    "is_deleted",
    "is_defaulted",
    "is_explicit",
    "is_final",
    "is_abstract",
    "is_polymorphic",
    "is_noexcept",
    "return_type_spelling",
}
COMMON_FIELDS = {"id", "name", "path", "position", "type_id", "file_id"}
