PROJECT_FIELDS = {
    "repository": {
        "id",
        "name",
        "kind",
        "remote_url",
        "active_clone_id",
        "semantic_universe_id",
    },
    "clone": {"id", "name", "repository_id", "path", "label"},
    "component": {
        "id",
        "name",
        "path",
        "kind",
        "version",
        "repository_id",
        "semantic_universe_id",
    },
    "directory": {"id", "name", "component_id", "path"},
    "file": {
        "id",
        "name",
        "path",
        "directory_id",
        "mtime",
        "md5",
        "compile_options",
        "driver",
        "working_directory",
        "indexed",
        "indexed_at",
        "args_overridden",
    },
}
