FACT_FIELDS = {
    "parameter": {
        "id",
        "owner_id",
        "position",
        "name",
        "type_id",
        "line",
        "col",
        "offset",
        "region_offset",
        "region_size",
        "file",
        "file_id",
        "is_pointer",
        "is_lvalue_reference",
        "is_rvalue_reference",
        "is_forwarding_reference",
        "is_const",
        "is_pack",
        "has_default",
        "default_expression",
        "default_kind",
        "default_value",
    },
    "template_parameter": {
        "id",
        "owner_id",
        "position",
        "name",
        "type_id",
        "is_parameter_pack",
        "is_non_type",
        "is_template_template",
    },
    "template_argument": {
        "id",
        "owner_id",
        "position",
        "value",
        "type_id",
        "kind",
        "pack_index",
        "is_pointer",
        "is_lvalue_reference",
        "is_rvalue_reference",
        "is_forwarding_reference",
        "is_const",
        "is_pack",
    },
    "edge": {
        "id",
        "source_id",
        "destination_id",
        "kind",
        "kind_id",
        "position",
        "access",
        "is_virtual_base",
        "is_implicit",
        "is_lexical",
        "count",
    },
    "site": {
        "id",
        "source_id",
        "destination_id",
        "kind",
        "kind_id",
        "position",
        "file_id",
        "file",
        "line",
        "col",
        "offset",
        "receiver_type_id",
        "certainty",
    },
    "definition": {"id", "symbol_id", "file_id", "file", "offset", "size"},
    "enumeration": {
        "id",
        "symbol_id",
        "underlying_type",
        "is_scoped",
        "has_fixed_underlying_type",
    },
    "enumerator": {"id", "symbol_id", "value", "initializer_expression"},
    "initializer": {
        "id",
        "symbol_id",
        "expression",
        "evaluated_kind",
        "evaluated_value",
    },
    "return_type": {"id", "symbol_id", "canonical_type"},
}
