FACTS_TABLES = {
    "symbol",
    "callable_return_type",
    "definition",
    "enumeration",
    "enumerator",
    "variable_initializer",
    "parameter",
    "parameter_default",
    "template_argument",
    "template_parameter",
    "relation",
    "relation_site",
    "include_dependency",
}

EVIDENCE_TABLES = {"expression_occurrence", "source_region"}

PROJECT_TABLES = {
    "semantic_universe",
    "repository",
    "clone",
    "component",
    "directory",
    "file",
    "project_registry",
}

COLUMNS = {
    "symbol": {
        "id",
        "node",
        "kind",
        "usr",
        "qualified_name",
        "line",
        "col",
        "offset",
        "is_definition",
        "is_noexcept",
        "is_volatile",
    },
    "relation": {"source_id", "destination_id", "kind", "position", "count"},
    "relation_site": {
        "source_id",
        "destination_id",
        "kind",
        "position",
        "file_id",
        "offset",
        "receiver_type_id",
        "certainty",
    },
    "file": {
        "id",
        "directory_id",
        "name",
        "compile_options",
        "driver",
        "working_directory",
        "indexed",
        "args_overridden",
    },
    "component": {"id", "path", "version", "repository_id"},
    "repository": {"id", "active_clone_id"},
    "expression_occurrence": {
        "occurrence_id",
        "identity",
        "owner_id",
        "target_id",
        "file_id",
        "line",
        "col",
        "offset",
        "size",
        "source_sha256",
        "expression_kind",
        "access",
        "freshness",
        "unavailable_reason",
    },
    "source_region": {
        "region_id",
        "identity",
        "symbol_id",
        "file_id",
        "line",
        "col",
        "offset",
        "size",
        "source_sha256",
        "symbol_kind",
        "freshness",
        "unavailable_reason",
    },
}
