CALLGRAPH_TABLES = {
    "callgraph_run",
    "callgraph_run_root",
    "callgraph_run_target",
    "callgraph_run_edge",
    "callgraph_run_frontier",
    "callgraph_run_recovery",
}

CALLGRAPH_COLUMNS = {
    "callgraph_run": {
        "run_id",
        "created_at",
        "project_path",
        "facts_path",
        "mode",
        "path_mode",
        "calls_scope",
        "components",
        "max_depth",
        "max_nodes",
        "max_edges",
        "time_limit_ms",
        "recover_missing",
        "status",
        "truncation_reason",
        "error",
    },
    "callgraph_run_root": {"run_id", "symbol_id", "usr"},
    "callgraph_run_target": {"run_id", "symbol_id", "usr"},
    "callgraph_run_edge": {
        "run_id",
        "source_id",
        "destination_id",
        "kind",
        "position",
        "file_id",
        "offset",
        "depth",
        "cycle",
    },
    "callgraph_run_frontier": {"run_id", "symbol_id", "reason"},
    "callgraph_run_recovery": {
        "run_id",
        "tu_file_id",
        "outcome",
        "diagnostic",
    },
}
