Feature: Native facts-tool database compatibility
  Scenario: Query a facts-tool generated pair through the public API
    Given a database pair generated by the native facts-tool
    When I query native symbols sites and project files
    Then native kinds ambiguity sites and both databases are preserved
